id: PEA34D30B
initial_creation_type: input
source_metadata:
  title: Trulshik Rinpoche Series
  language: bo
  description: Texts by and about Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö ('khrul
    zhig ngag dbang chos kyi blo gros, 1924–2011), one of the teachers of His Holiness
    the Fourteenth Dalai Lama.
  volume:
    725151f57011413ca05a3c99148df204:
      title: Advice for Retreat
      parent: Advice
    246198931528470286c12306bf6404e6:
      title: Advice for Tenzin Jamchen
      parent: Advice
    5ef9f495835e42759ed1b8e2bdde4d83:
      title: Advice in Four Lines
      parent: Advice
    bf8f17abe3c94513ba602a15b08f5b06:
      title: A Prayer for Translators
      parent: Aspiration Prayers
    0d202d3da6614314bd26061f30a57e47:
      title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
      parent: Aspiration Prayers
    0db925b830314f6ab185ead883ad48db:
      title: Prayer of the View, Meditation and Conduct
      parent: Aspiration Prayers
    2f30ccb634f9437e852e31a5b4076f14:
      title: Profound Prayer of Aspiration
      parent: Aspiration Prayers
    62cee75982a14fd1bef218d9be929fc3:
      title: 'The Quintessential Blessing: A Guru Yoga'
      parent: Guru Yoga
    faed46890f1a4011a8a7f406afdca05f:
      title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong
        Trulshik Rinpoche, the Representative of Guru Rinpoche'
      parent: Long Life Prayers
    559322febb3c4379b80e7ccb83e735d3:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Long Life Prayers
    76f18809f922492eb705f35bbf54d8e8:
      title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
      parent: Long Life Prayers
    3791671e4eab45058323f2047e21b140:
      title: Long Life Prayer for Lodi Gyari Rinpoche
      parent: Long Life Prayers
    9224148cd5414ff68efceba92bbb636b:
      title: Long Life Prayer for Mayum Tsering Wangmo
      parent: Long Life Prayers
    f810e073dcc6413a92503d88bef755fd:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    10a556d68dae4503b17a11e93e6cef01:
      title: Prayer for the Long Life of Dilgo Khyentsé II of Shechen, Urgyen Tenzin
        Jigme Lhundrup
      parent: Long Life Prayers
    ed29dc71908b48b1897e2a9c0e7dcdb2:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Long Life Prayers
    b60ec945f30848dc81f9e9bf63798f5c:
      title: Prayer for the Long Life of Sogyal Rinpoche—chimé kunnyé
      parent: Long Life Prayers
    d804aeb61a90436eb8b03b35982f1880:
      title: Prayer for the Long Life of Sogyal Rinpoche—sönam jewé
      parent: Long Life Prayers
    04c32cedeb954fa0b4b0fbfcc678d792:
      title: Prayer for the Long Life of Taklung Tsetrul Rinpoche
      parent: Long Life Prayers
    f8a7f5e3456049af965f9b7a7ca9065b:
      title: The Attainment of Immortality
      parent: Long Life Prayers
    ce265eeb57b14208864c12edfeca0ad6:
      title: A Homage to His Holiness the Dalai Lama
      parent: Praise
    6321eeda696649f189c59e0bc4a77c3e:
      title: Verses of Homage
      parent: Praise
    6451b5378c8c404c80d575b647a3c00b:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    6c842a05615d476da3b0066733c86512:
      title: A Record of the Successive Incarnations
      parent: Prayers
    e0701772c5b14647a4725578a6968044:
      title: 'Gateway for the Faithful: A Supplication Recalling the Lives and Liberation
        of Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö'
      parent: Prayers
    759acfcce46340a9845b21ccc090be33:
      title: A Brief Daily Practice of Damdrip Nyepa Kunsel
      parent: Sādhanas
    f6405275a3ab4ef4a09c42a274070fc2:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:52:59.298591'
last_modified_at: '2022-03-01T01:52:59.298594'
